[package]
name = "gameshow-v2"
version = "0.1.0"
authors = ["FlixCoder <xbbfanx@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
